multinode: false

# Use DRA instead of device plugins
dra:
  enabled: true
  type: "intel-gaudi"
  claimTemplates:
  - name: intel-gaudi
    class: gaudi.intel.com
    match: "exactly"
    count: 1
  
modelArtifacts:
  uri: "hf://meta-llama/Llama-3.2-3B-Instruct"
  size: 100Gi
  authSecretName: "llm-d-hf-token"
  name: "meta-llama/Llama-3.2-3B-Instruct"

routing:
  servicePort: 8000

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.4.0-rc.1
    connector: nixlv2
    secure: false

decode:
  create: true
  replicas: 1
  monitoring:
    podmonitor:
      enabled: false
      portName: "metrics" # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: vllm
    image: "opea/vllm-gaudi:1.22.0"
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c"]
    args:
      - |
        vllm serve meta-llama/Llama-3.2-3B-Instruct \
          --port 8200 \
          --enforce-eager \
          --gpu-memory-utilization 0.9 \
          --tensor-parallel-size 1 --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both","kv_buffer_device":"cpu"}'
    env:
      - name: HABANA_VISIBLE_DEVICES
        value: "0,1,2,3,4,5,6,7"
      - name: OMPI_MCA_btl_vader_single_copy_mechanism
        value: "none"
      - name: HABANA_LOGS
        value: "/tmp/habana_logs"
      - name: UCX_TLS 
        value: "tcp"
      - name: RANK
        value: "6"
      - name: VLLM_LOGGING_LEVEL
        value: "DEBUG"
      - name: VLLM_SKIP_WARMUP
        value: "true"
      - name: PT_HPU_LAZY_MODE
        value: "1"
      - name: PT_HPU_ENABLE_LAZY_COLLECTIVES
        value: "true"
      - name: LD_LIBRARY_PATH
        value: "/usr/lib/nixl_ofi:/usr/local/lib:/usr/lib:/opt/amazon/openmpi/lib:/usr/lib/habanalabs"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: DO_NOT_TRACK
        value: "1"
      - name: VLLM_USE_V1
        value: "1"
    ports:
      - containerPort: 8200
        name: metrics
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
      - name: metrics-volume
        mountPath: /.config
      - name: shm
        mountPath: /dev/shm
      - name: torch-compile-cache
        mountPath: /.cache
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: "100Gi"
    - name: torch-compile-cache
      emptyDir: {}

prefill:
  create: true
  replicas: 1
  monitoring:
    podmonitor:
      enabled: false
      portName: "metrics" # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: vllm
    image: opea/vllm-gaudi:1.22.0
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c"]
    args:
      - |
        vllm serve meta-llama/Llama-3.2-3B-Instruct \
          --port 8000 \
          --enforce-eager \
          --gpu-memory-utilization 0.9 \
          --tensor-parallel-size 1 --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both","kv_buffer_device":"cpu"}'
    env:
      - name: HABANA_VISIBLE_DEVICES
        value: "0,1,2,3,4,5,6,7"
      - name: OMPI_MCA_btl_vader_single_copy_mechanism
        value: "none"
      - name: HABANA_LOGS
        value: "/tmp/habana_logs"
      - name: UCX_TLS 
        value: "tcp"
      - name: RANK
        value: "7"
      - name: VLLM_LOGGING_LEVEL
        value: "DEBUG"
      - name: VLLM_SKIP_WARMUP
        value: "true"
      - name: PT_HPU_LAZY_MODE
        value: "1"
      - name: PT_HPU_ENABLE_LAZY_COLLECTIVES
        value: "true"
      - name: LD_LIBRARY_PATH
        value: "/usr/lib/nixl_ofi:/usr/local/lib:/usr/lib:/opt/amazon/openmpi/lib:/usr/lib/habanalabs"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: DO_NOT_TRACK
        value: "1"
      - name: VLLM_USE_V1
        value: "1"
    ports:
      - containerPort: 8000
        name: metrics
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
      - name: metrics-volume
        mountPath: /.config
      - name: shm
        mountPath: /dev/shm
      - name: torch-compile-cache
        mountPath: /.cache
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: "100Gi"
    - name: torch-compile-cache
      emptyDir: {}


